config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/routes', to: 'routes#index'
  get '/red', to: 'lines#red'
  get '/blue', to: 'lines#blue'
  get '/orange', to: 'lines#orange'
  get '/silver', to: 'lines#silver'
  get '/yellow', to: 'lines#yellow'
  get '/green', to: 'lines#green'

  resources :station, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line.rb
class Line < ApplicationRecord
  validates_presence_of :name

  has_many :line_stations
  has_many :stations, through: :line_stations
end

app/models/line_station.rb
class LineStation < ApplicationRecord
  belongs_to :line
  belongs_to :station
end

app/models/station.rb
class Station < ApplicationRecord
  validates_presence_of :name, :station_code

  has_many :line_stations
  has_many :lines, through: :line_stations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController

  def red
    @red_stations = Line.find_by_name('red').stations
  end

  def blue
    @blue_stations = Line.find_by_name('blue').stations
  end

  def green
    @green_stations = Line.find_by_name('green').stations
  end

  def yellow
    @yellow_stations = Line.find_by_name('yellow').stations
  end

  def silver
    @silver_stations = Line.find_by_name('silver').stations
  end

  def orange
    @orange_stations = Line.find_by_name('orange').stations
  end

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController

  def index

  end

end

app/controllers/station_controller.rb
class StationController < ApplicationController

  def show
    current_station = Station.find(params[:id].to_i)
    @station = current_station
    lines = current_station.lines
    @names = []
    lines.each do |line|
      @names << line.name.capitalize
    end
    find_trains = TrainUpdateService.new(current_station.station_code).get_trains
    unless current_station.alternate_station_code.nil?
      alternate_trains = TrainUpdateService.new(current_station.alternate_station_code).get_trains
      find_trains << alternate_trains
    end
    @trains = TrainSorterService.new(find_trains.flatten)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Metro Helper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: "navs/top_nav" %>
    <%= yield %>
  </body>
</html>

app/views/lines/blue.html.erb
<main>
  <h1 class="heading">Blue Line</h1>
  <h3 class="sub-heading">Select What Station You Are Using</h3>
  <div class="stations">
    <% @blue_stations.each do |station| %>
      <div class="station">
        <%= link_to station.name, station_path(station) %>
      </div>
    <% end %>
  </div>
</main>

app/views/lines/green.html.erb
<main>
  <h1 class="heading">Green Line</h1>
  <h3 class="sub-heading">Select What Station You Are Using</h3>
  <div class="stations">
    <% @green_stations.each do |station| %>
      <div class="station">
        <%= link_to station.name, station_path(station) %>
      </div>
    <% end %>
  </div>
</main>

app/views/lines/orange.html.erb
<main>
  <h1 class="heading">Orange Line</h1>
  <h3 class="sub-heading">Select What Station You Are Using</h3>
  <div class="stations">
    <% @orange_stations.each do |station| %>
      <div class="station">
        <%= link_to station.name, station_path(station) %>
      </div>
    <% end %>
  </div>
</main>

app/views/lines/red.html.erb
<main>
  <h1 class="heading">Red Line</h1>
  <h3 class="sub-heading">Select What Station You Are Using</h3>
  <div class="stations">
    <% @red_stations.each do |station| %>
      <div class="station">
        <%= link_to station.name, station_path(station) %>
      </div>
    <% end %>
  </div>
</main>

app/views/lines/silver.html.erb
<main>
  <h1 class="heading">Silver Line</h1>
  <h3 class="sub-heading">Select What Station You Are Using</h3>
  <div class="stations">
    <% @silver_stations.each do |station| %>
      <div class="station">
        <%= link_to station.name, station_path(station) %>
      </div>
    <% end %>
  </div>
</main>

app/views/lines/yellow.html.erb
<main>
  <h1 class="heading">Yellow Line</h1>
  <h3 class="sub-heading">Select What Station You Are Using</h3>
  <div class="stations">
    <% @yellow_stations.each do |station| %>
      <div class="station">
        <%= link_to station.name, station_path(station) %>
      </div>
    <% end %>
  </div>
</main>

app/views/navs/_top_nav.html.erb
<div class="top-nav">
  <h3><%= link_to "Select Your Line", '/routes' %></h3>
</div>

app/views/routes/index.html.erb
<main>
  <h1 class="heading">DC Metro Helper</h1>
  <h3 class="sub-heading">Select What Line You Are Travelling</h3>
  <div class="lines">
    <div class="line" id='red'>
      <%= link_to "Red", red_path %>
    </div>
    <div class="line" id='blue'>
      <%= link_to "Blue", blue_path %>
    </div>
    <div class="line" id='yellow'>
      <%= link_to "Yellow", yellow_path %>
    </div>
    <div class="line" id='green'>
      <%= link_to "Green", green_path %>
    </div>
    <div class="line" id='orange'>
      <%= link_to "Orange", orange_path %>
    </div>
    <div class="line" id='silver'>
      <%= link_to "Silver", silver_path %>
    </div>
  </div>
</main>

app/views/station/show.html.erb
<main>
  <h1 class="heading"><%= @station.name %></h1>
  <h3 class="sub-heading">Lines: <%= @names.join(', ') %></h3>

  <div class="lines">
    <% unless @trains.red_trains.count == 0 %>
      <% train_string = @trains.red_trains.map do |train| %>
        <% "#{train.size} car train to #{train.destination} in #{train.time} minutes" %>
      <% end.join(', ') %>
      <h3>Red Trains:</h3> <p><%= train_string %></p>
    <% end %>

    <% unless @trains.blue_trains.count == 0 %>
      <% train_string = @trains.blue_trains.map do |train| %>
        <% "#{train.size} car train to #{train.destination} in #{train.time} minutes" %>
      <% end.join(', ') %>
      <h3>Blue Trains:</h3> <p><%= train_string %></p>
    <% end %>

    <% unless @trains.green_trains.count == 0 %>
      <% train_string = @trains.green_trains.map do |train| %>
        <% "#{train.size} car train to #{train.destination} in #{train.time} minutes" %>
      <% end.join(', ') %>
      <h3>Green Trains:</h3> <p><%= train_string %></p>
    <% end %>

    <% unless @trains.yellow_trains.count == 0 %>
      <% train_string = @trains.yellow_trains.map do |train| %>
        <% "#{train.size} car train to #{train.destination} in #{train.time} minutes" %>
      <% end.join(', ') %>
      <h3>Yellow Trains:</h3> <p><%= train_string %></p>
    <% end %>

    <% unless @trains.silver_trains.count == 0 %>
      <% train_string = @trains.silver_trains.map do |train| %>
        <% "#{train.size} car train to #{train.destination} in #{train.time} minutes" %>
      <% end.join(', ') %>
      <h3>Silver Trains:</h3> <p><%= train_string %></p>
    <% end %>

    <% unless @trains.orange_trains.count == 0 %>
      <% train_string = @trains.orange_trains.map do |train| %>
        <% "#{train.size} car train to #{train.destination} in #{train.time} minutes" %>
      <% end.join(', ') %>
      <h3>Orange Trains:</h3> <p><%= train_string %></p>
    <% end %>
  </div>
</main>